### ISSUE TITLE
Installation issue on MW 1.39: invalid magic word 'network'

### ISSUE THREAD

**Issue by D-Groenewegen** [ProfessionalWiki/Network#67]
- MediaWiki 1.39.2
- PHP 8.0.28 (litespeed)
- MariaDB 10.3.38-MariaDB-0+deb10u1
- ICU 63.1

I tried installing the latest version of this extension (currently 2.0.0) on a new installation of MW 1.39.2. When I activate it, I get a fatal exception saying that `network` is an invalid magic word.

The full backtrace is: 

```
Importing from smw.groups.json ...
   ... smw/schema:Group:Schema properties ...MWException from line 129 of [...]/includes/MagicWord.php: Error: invalid magic word 'network'
#0 [...]/includes/MagicWordFactory.php(231): MagicWord->load()
#1 [...]/includes/parser/Parser.php(5029): MagicWordFactory->get()
#2 [...]/extensions/Network/src/EntryPoints/NetworkFunction.php(30): Parser->setFunctionHook()
#3 [...]/includes/HookContainer/HookContainer.php(338): MediaWiki\Extension\Network\EntryPoints\NetworkFunction::onParserFirstCallInit()
#4 [...]/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#5 [...]/includes/HookContainer/HookRunner.php(2914): MediaWiki\HookContainer\HookContainer->run()
#6 [...]/includes/parser/Parser.php(560): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit()
#7 [...]/includes/parser/ParserFactory.php(216): Parser->__construct()
#8 [...]/includes/parser/ParserFactory.php(233): ParserFactory->create()
#9 [...]/includes/ServiceWiring.php(1266): ParserFactory->getMainInstance()
#10 [...]/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#11 [...]/vendor/wikimedia/services/src/ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#12 [...]/includes/MediaWikiServices.php(301): Wikimedia\Services\ServiceContainer->getService()
#13 [...]/includes/MediaWikiServices.php(1417): MediaWiki\MediaWikiServices->getService()
#14 [...]/includes/ServiceWiring.php(1409): MediaWiki\MediaWikiServices->getParser()
#15 [...]/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#16 [...]/vendor/wikimedia/services/src/ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#17 [...]/includes/MediaWikiServices.php(301): Wikimedia\Services\ServiceContainer->getService()
#18 [...]/includes/MediaWikiServices.php(1491): MediaWiki\MediaWikiServices->getService()
#19 [...]/includes/ServiceWiring.php(2297): MediaWiki\MediaWikiServices->getParsoidSiteConfig()
#20 [...]/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#21 [...]/vendor/wikimedia/services/src/ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#22 [...]/includes/MediaWikiServices.php(301): Wikimedia\Services\ServiceContainer->getService()
#23 [...]/includes/ServiceWiring.php(1364): MediaWiki\MediaWikiServices->getService()
#24 [...]/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#25 [...]/vendor/wikimedia/services/src/ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#26 [...]/includes/MediaWikiServices.php(301): Wikimedia\Services\ServiceContainer->getService()
#27 [...]/includes/MediaWikiServices.php(1466): MediaWiki\MediaWikiServices->getService()
#28 [...]/includes/ServiceWiring.php(1238): MediaWiki\MediaWikiServices->getParsoidOutputAccess()
#29 [...]/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#30 [...]/vendor/wikimedia/services/src/ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#31 [...]/includes/MediaWikiServices.php(301): Wikimedia\Services\ServiceContainer->getService()
#32 [...]/includes/MediaWikiServices.php(1405): MediaWiki\MediaWikiServices->getService()
#33 [...]/includes/page/WikiPage.php(258): MediaWiki\MediaWikiServices->getPageUpdaterFactory()
#34 [...]/includes/page/WikiPage.php(1782): WikiPage->getPageUpdaterFactory()
#35 [...]/includes/page/WikiPage.php(1881): WikiPage->newPageUpdater()
#36 [...]/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(167): WikiPage->doUserEditContent()
#37 [...]/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(142): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent()
#38 [...]/includes/libs/rdbms/database/Database.php(2501): SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}()
#39 [...]/includes/libs/rdbms/database/Database.php(2412): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks()
#40 [...]/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle()
#41 [...]/includes/libs/rdbms/database/DBConnRef.php(628): Wikimedia\Rdbms\DBConnRef->__call()
#42 [...]/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(784): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle()
#43 [...]/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(143): SMW\MediaWiki\Connection\Database->onTransactionIdle()
#44 [...]/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create()
#45 [...]/extensions/SemanticMediaWiki/src/Importer/Importer.php(142): SMW\Importer\ContentCreators\DispatchingContentCreator->create()
#46 [...]/extensions/SemanticMediaWiki/src/Importer/Importer.php(120): SMW\Importer\Importer->doImport()
#47 [...]/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1510): SMW\Importer\Importer->runImport()
#48 [...]/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete()
#49 [...]/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#50 [...]/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run()
#51 [...]/extensions/SemanticMediaWiki/src/MediaWiki/HookDispatcher.php(276): Hooks::run()
#52 [...]/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(279): SMW\MediaWiki\HookDispatcher->onInstallerAfterCreateTablesComplete()
#53 [...]/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(452): SMW\SQLStore\Installer->install()
#54 [...]/extensions/SemanticMediaWiki/src/Store.php(488): SMW\SQLStore\SQLStore->setup()
#55 [...]/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore()
#56 [...]/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates()
#57 [...]/maintenance/update.php(202): DatabaseUpdater->doUpdates()
#58 [...]/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#59 [...]/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#60 [...]/maintenance/update.php(312): require_once('...')
#61 {main}
```

**Comment by krabina** [comment]
Working for me: 
- https://test.knowledge.wiki/Network_Test
- https://test.knowledge.wiki/Spezial:Network
- https://test.knowledge.wiki/Spezial:Version
